name: tests

on: [push, pull_request]

env:
  build_dir: "build"
  build_type: "Release"

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ g++, clang++ ]
    steps:
      - uses: actions/checkout@v3
      - name: Install Google Test
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtest-dev
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp lib/*.a /usr/lib
      - name: Build
        run: |
          cmake -B build -S .
          cmake --build build

      - name: Run Tests
        run: ./build/dns_cache_test